persistence:
  config:
    storageClass: "local-path"
    size: 5Gi
  media:
    storageClass: "local-path"
    size: 100Gi

ingress:
  enabled: true
  className: "tailscale"
  hosts:
    - host: "jellyfin.hound-avior.ts.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "jellyfin.hound-avior.ts.net"
