queueMode:
  enabled: false

database:
  type: sqlite

persistence:
  enabled: true
  storageClass: "local-path"
  size: 5Gi

ingress:
  enabled: true
  className: "tailscale"
  hosts:
    - host: "n8n.hound-avior.ts.net"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "n8n.hound-avior.ts.net"

webhook:
  url: "https://n8n.hound-avior.ts.net"
