apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.102.4
      helm:
        valueFiles:
          - $values/apps/tailscale-operator/values.yaml

    - repoURL: https://github.com/maxwowo/homelab.git
      targetRevision: main
      path: apps/tailscale-operator/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
